# .streamlit/secrets.toml

NEWS_API_KEY = "pub_3635376fbe864620b7ed18f787df3a42"
JINA_API_KEY = "jina_a7851b55549844c1b8354d8b8592d6e8fNdUTGU6f3OjGFzizsEPMyDnbTP_"
GEMINI_API_KEY = "AIzaSyAPVibcwY6yfjwgAXPn0hO2gC_VnUu3fbQ"